from os import getenv

GOOGLE_CLIENT_ID = getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = getenv('GOOGLE_CLIENT_SECRET')

X_CLIENT_ID = getenv('X_CLIENT_ID')
X_CLIENT_SECRET = getenv('X_CLIENT_SECRET')
